In [114]:
import pandas as pd

In [115]:
data=pd.read_csv("Advertising.csv")

In [116]:
data.head()

   ID     TV  Radio  Newspaper  Sales
0   1  230.1   37.8       69.2   22.1
1   2   44.5   39.3       45.1   10.4
2   3   17.2   45.9       69.3    9.3
3   4  151.5   41.3       58.5   18.5
4   5  180.8   10.8       58.4   12.9

In [117]:
data.shape

(200, 5)

In [118]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         200 non-null    int64
 1   TV         200 non-null    float64
 2   Radio      200 non-null    float64
 3   Newspaper  200 non-null    float64
 4   Sales      200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [119]:
data.isnull().sum()

ID           0
TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [120]:
data.duplicated().sum()

np.int64(0)

In [121]:
x=data.drop("Sales",axis=1)

In [122]:
y=data["Sales"]

In [123]:
x.head()

   ID     TV  Radio  Newspaper
0   1  230.1   37.8       69.2
1   2   44.5   39.3       45.1
2   3   17.2   45.9       69.3
3   4  151.5   41.3       58.5
4   5  180.8   10.8       58.4

In [124]:
from sklearn.model_selection import train_test_split

In [125]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [126]:
x_train.shape

(160, 4)

In [127]:
x_test.shape

(40, 4)

In [128]:
from sklearn.linear_model import LinearRegression

In [129]:
lr=LinearRegression()

In [130]:
lr.fit(x_train,y_train)

LinearRegression()

In [131]:
y_pred=lr.predict(x_test)

In [132]:
comparision=pd.DataFrame({
    'Actual':y_test.values,
    'Predicted':y_pred
})

In [133]:
comparision

    Actual  Predicted
0     16.9  16.412277
1     22.4  20.843193
2     21.4  21.511869
3      7.3  10.653100
4     24.7  22.124058
5     12.6  13.123835
6     22.3  21.037489
7      8.4   7.503854
8     11.5  13.647870
9     14.9  15.120409
10     9.5   9.020556
11     8.7   6.706666
12    11.9  14.401551
13     5.3   8.886090
14    10.3   9.743533
15    11.7  12.215520
16     5.5   8.713709
17    16.6  16.294145
18    11.3  10.268023
19    18.9  18.804982
20    19.7  19.588647
21    12.5  13.223183
22    10.9  12.364787
23    22.2  21.314736
24     9.3   7.797347
25     8.1   5.781900
26    21.7  20.749348
27    13.4  11.954767
28    10.6   9.199109
29     5.7   8.521787
30    10.6  12.404313
31    11.3   9.948652
32    23.7  21.368803
33     8.7  12.253748
34    16.1  18.299435
35    20.7  20.133474
36    11.6  14.074646
37    20.8  20.885947
38    11.9  11.052150
39     6.9   4.551687

In [134]:
from sklearn.metrics import mean_absolute_error

In [135]:
mae=mean_absolute_error(y_test,y_pred)

In [136]:
mae

1.4650601050102927

In [137]:
from sklearn.metrics import r2_score

In [138]:
r2=r2_score(y_test,y_pred)

In [139]:
r2

0.8986489151417081

In [142]:
def pred_sales(id,tv,radio,newspaper):  
    prediction=lr.predict([[
        id,
        tv,
        radio,
        newspaper
    ]])

    return prediction[0]

In [144]:
rs=pred_sales(
    id=150,  
    tv=100, 
    radio=30,
    newspaper=20
)

C:\Users\hafiz\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [149]:
rs

np.float64(13.213351596518814)