In [29]:
import pandas as pd
import numpy as np 
import matplotlib as plt

In [30]:
data=pd.read_csv("insurance.csv")

In [31]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [33]:
data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [34]:
data.duplicated().sum()

np.int64(1)

In [35]:
data[data.duplicated()]

     age   sex    bmi  children smoker     region    charges
581   19  male  30.59         0     no  northwest  1639.5631

In [36]:
data.drop_duplicates(inplace=True)

In [37]:
data["smoker"]=data["smoker"].replace({"yes":1,"no":0})

C:\Users\hafiz\AppData\Local\Temp\ipykernel_18508\3261917912.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["smoker"]=data["smoker"].replace({"yes":1,"no":0})

In [38]:
data["sex"]=data["sex"].replace({"male":1,"female":0})

C:\Users\hafiz\AppData\Local\Temp\ipykernel_18508\3396628019.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["sex"]=data["sex"].replace({"male":1,"female":0})

In [39]:
data=pd.get_dummies(data,columns=["region"],dtype=int)

In [40]:
data.head()

,age,sex,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,0,0,0,1
1,18,1,33.770,1,0,1725.55230,0,0,1,0
2,28,1,33.000,3,0,4449.46200,0,0,1,0
3,33,1,22.705,0,0,21984.47061,0,1,0,0
4,32,1,28.880,0,0,3866.85520,0,1,0,0

In [41]:
y=data["charges"]

In [42]:
x=data.drop("charges",axis=1)

In [43]:
from sklearn.model_selection import train_test_split

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [53]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1069, 9)
(268, 9)
(1069,)
(268,)

In [54]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [55]:
lr.fit(x_train,y_train)

LinearRegression()

In [56]:
y_pred=lr.predict(x_test)

In [59]:
comparision=pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

In [61]:
comparision.head(10)

        Actual     Predicted
0   8688.85885   8143.693884
1   5708.86700   5737.115683
2  11436.73815  14369.314876
3  38746.35510  31745.513636
4   4463.20510   8962.386657
5   9304.70190  13149.722353
6  38511.62830  30446.760679
7   2150.46900   1453.288813
8   7345.72660  10633.018402
9  10264.44210  11318.943794

In [62]:
from sklearn.metrics import mean_absolute_error

In [64]:
mae=mean_absolute_error(y_test,y_pred)

In [65]:
mae

4177.045561036321

In [66]:
from sklearn.metrics import r2_score

In [67]:
r2=r2_score(y_test,y_pred)

In [68]:
r2

0.8069287081198011

In [69]:
def predict_insurance(age, sex, bmi, children, smoker, region):

    region_northeast = 0
    region_northwest = 0
    region_southeast = 0
    region_southwest = 0

    if region == "northeast":
        region_northeast = 1
    elif region == "northwest":
        region_northwest = 1
    elif region == "southeast":
        region_southeast = 1
    elif region == "southwest":
        region_southwest = 1

    prediction = lr.predict([[
        age,
        sex,
        bmi,
        children,
        smoker,
        region_northeast,
        region_northwest,
        region_southeast,
        region_southwest
    ]])

    return prediction[0]

In [71]:
predict_insurance(20,1,25,2,0,"nortwest")

C:\Users\hafiz\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

np.float64(2331.120850448129)