In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("Real estate.csv")

In [5]:
data.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [6]:
data.shape

(414, 8)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   No                                      414 non-null    int64
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB

In [9]:
data.isnull().sum()

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [10]:
data.duplicated().sum()

np.int64(0)

In [11]:
data=data.drop("No",axis=1)

In [13]:
data.columns

Index(['X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [16]:
x=data.drop('Y house price of unit area',axis=1)

In [17]:
y=data['Y house price of unit area']

In [20]:
x.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
0,2012.917,32.0,84.87882,10,24.98298,121.54024
1,2012.917,19.5,306.59470,9,24.98034,121.53951
2,2013.583,13.3,561.98450,5,24.98746,121.54391
3,2013.500,13.3,561.98450,5,24.98746,121.54391
4,2012.833,5.0,390.56840,5,24.97937,121.54245

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
x_train.shape

(331, 6)

In [27]:
x_test.shape

(83, 6)

In [28]:
y_train.shape

(331,)

In [29]:
y_test.shape

(83,)

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
lr=LinearRegression()

In [33]:
lr.fit(x_train,y_train)

LinearRegression()

In [34]:
y_pred=lr.predict(x_test)

In [35]:
comparrision=pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":y_pred
})

In [36]:
comparrision

    Actual  Predicted
0     45.1  47.886254
1     42.3  41.164046
2     52.2  44.273014
3     37.3  40.197615
4     22.8  27.513265
..     ...        ...
78    25.0  40.368699
79    23.5  33.091396
80    35.6  42.327834
81    46.1  43.353985
82    26.2  28.439798

[83 rows x 2 columns]

In [37]:
from sklearn.metrics import mean_absolute_error

In [38]:
mae=mean_absolute_error(y_test,y_pred)

In [39]:
mae

5.3053556900741405

In [40]:
from sklearn.metrics import r2_score

In [41]:
r2=r2_score(y_test,y_pred)

In [42]:
r2

0.6810580555095782

In [48]:
def pred_price(): 
    transaction_date=float(input("Enter  transaction date: "))
    house_age=float(input("Enter house age: "))
    mrt_distance=float(input("Enter Metro distance: "))
    convenience_store =int(input("Enter convenience store: "))
    latitued=float(input("Enter latitued: "))
    longitued=float(input("Enter longitued: "))

    prediction=lr.predict([[
        transaction_date, 
        house_age, 
        mrt_distance, 
        convenience_store, 
        latitued, 
        longitued
    ]])
    return prediction[0]

In [50]:
pred_price()

Enter  transaction date:  2013.5
Enter house age:  20
Enter Metro distance:  500
Enter convenience store:  5
Enter latitued:  24.98
Enter longitued:  121.54

C:\Users\hafiz\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

np.float64(45.3297897491866)