In [24]:
import pandas as pd

In [25]:
data=pd.read_csv("Student_Performance.csv")

In [26]:
data.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91
1,4,82,No,4,2,65
2,8,51,Yes,7,2,45
3,5,52,Yes,5,2,36
4,7,75,No,8,5,66

In [27]:
data.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  int64
dtypes: int64(5), object(1)
memory usage: 468.9+ KB

In [29]:
data.duplicated().sum()

np.int64(127)

In [30]:
data=data.drop_duplicates()

In [31]:
data.shape

(9873, 6)

In [32]:
data["Extracurricular Activities"].unique()

array(['Yes', 'No'], dtype=object)

In [33]:
data["Extracurricular Activities"]=data["Extracurricular Activities"].replace({
    "Yes":1,
    "No":0
})

C:\Users\hafiz\AppData\Local\Temp\ipykernel_12384\3284803513.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Extracurricular Activities"]=data["Extracurricular Activities"].replace({

In [34]:
data.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91
1,4,82,0,4,2,65
2,8,51,1,7,2,45
3,5,52,1,5,2,36
4,7,75,0,8,5,66

In [35]:
x=data.drop('Performance Index',axis=1)
y=data['Performance Index']

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
lr=LinearRegression()

In [40]:
lr.fit(x_train,y_train)

LinearRegression()

In [41]:
y_pred=lr.predict(x_test)

In [42]:
comparision=pd.DataFrame({
    'Actual':y_test.values,
    'Predicted':y_pred
})

In [43]:
comparision

      Actual  Predicted
0         47  46.480013
1         76  80.285379
2         62  61.065188
3         23  22.706315
4         76  74.836868
...      ...        ...
1970      19  18.277835
1971      39  40.310084
1972      77  77.084436
1973      88  86.246766
1974      34  35.879338

[1975 rows x 2 columns]

In [45]:
from sklearn.metrics import mean_absolute_error

In [47]:
mae=mean_absolute_error(y_test,y_pred)

In [48]:
mae

1.646970398425557

In [49]:
from sklearn.metrics import r2_score

In [50]:
r2=r2_score(y_test,y_pred)

In [51]:
r2

0.9884301209927054

In [52]:
data.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [69]:
def pred_performence(HoursStudied,PreviousScores,ExtracurricularActivities,SleepHours, SampleQuestionPapersPracticed):  
    prediction=lr.predict([[
        HoursStudied,
        PreviousScores,
        ExtracurricularActivities,
        SleepHours,
        SampleQuestionPapersPracticed
    ]])

    return prediction[0]

In [72]:
new_data=pred_performence(
    HoursStudied=3, 
    PreviousScores=73, 
    ExtracurricularActivities=1, 
    SleepHours=4,
    SampleQuestionPapersPracticed=10
)

C:\Users\hafiz\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [73]:
new_data

np.float64(53.26630900197992)